### ISSUE TITLE
if not allow read sms or read contacts permission, will crash

### ISSUE THREAD

**Issue by kymjs** [qklabs/qksms#123]
if not allow read sms or read contacts permission, will crash. 

Caused by: java.lang.NullPointerException
            at com.moez.QKSMS.ui.dialog.DefaultSmsHelper.<init>(DefaultSmsHelper.java:37)
            at com.moez.QKSMS.ui.MainActivity.onActivityResult(MainActivity.java:305)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)

**Comment by moezbhatti** [comment]
How do you reproduce this?

**Comment by kymjs** [comment]
On a custom rom, the application calls permissions, user can refuse. 
![Uploading Screenshot_2015-08-18-18-04-05-518_QKSMS.png…](1st)
![Uploading Screenshot_2015-08-18-18-04-12-007_QKSMS.png…](2nd)
crash...
![Uploading QQ20150818-1@2x.png…](logcat)

**Comment by kymjs** [comment]
https://github.com/qklabs/qksms/pull/129
