### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#265]
<a href="https://app.crittercism.com/developers/crash-details/f3129a3df0010296490b2457a7f7fe701997616ed69d7b59c8d38feb"> View Crash Report on Crittercism </a> 

 Reported by: Moez Bhatti (moez@qklabs.com)

Status: Unresolved

This Crash occured 1240 times for 866 users

0 java.lang.RuntimeException: An error occured while executing doInBackground()
1 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
2 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
3 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
4 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
5 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
6 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
7 	at java.lang.Thread.run(Thread.java:818)
8 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
9 	at com.moez.QKSMS.data.Conversation.loadFromThreadId(Conversation.java:1286)
10 	at com.moez.QKSMS.data.Conversation.<init>(Conversation.java:117)
11 	at com.moez.QKSMS.data.Conversation.get(Conversation.java:151)
12 	at com.moez.QKSMS.ui.messagelist.MessageListFragment$LoadConversationTask.doInBackground(MessageListFragment.java:1421)
13 	at com.moez.QKSMS.ui.messagelist.MessageListFragment$LoadConversationTask.doInBackground(MessageListFragment.java:1412)
14 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
15 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
16 	... 3 more
17 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
18 	at com.moez.QKSMS.data.Conversation.loadFromThreadId(Conversation.java:1286)
19 	at com.moez.QKSMS.data.Conversation.<init>(Conversation.java:117)
20 	at com.moez.QKSMS.data.Conversation.get(Conversation.java:151)
21 	at com.moez.QKSMS.ui.messagelist.MessageListFragment$LoadConversationTask.doInBackground(MessageListFragment.java:1421)
22 	at com.moez.QKSMS.ui.messagelist.MessageListFragment$LoadConversationTask.doInBackground(MessageListFragment.java:1412)
23 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
24 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
25 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
26 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
27 	at java.lang.Thread.run(Thread.java:818)

**Comment by moezbhatti** [comment]
Should be fixed with that commit. Will wait until release to confirm

**Comment by moezbhatti** [comment]
Should also fix https://app.crittercism.com/developers/crash-details/544b0c7a466eda142a000001/93887d308c731af2873afa8834dae81e3411ff58f49b39aba20d130a
